# -*- coding: utf-8 -*-
"""baseline_schema

Revision ID: 0001
Revises:
Create Date: 2026-10-01

基线迁移：创建全部业务表（18 张）。

说明
----
1. 本迁移由 ``scripts/gen_baseline_migration.py`` 离线生成，
   内容等价于对空库执行 ``Base.metadata.create_all()``，
   并已通过 ``scripts/verify_migration_parity.py`` 逐项校验一致。
2. 模型中的 ``JSONType`` / ``GUID`` 是 TypeDecorator，此处直接写标准类型
   （JSONB / UUID），使迁移文件自包含、不依赖应用代码演进。
3. 对「已由 create_all 建表」的存量数据库，**不要执行本迁移**，而应标记为已应用：

       python -m alembic stamp head

   此后所有结构变更都通过新迁移进行，不再使用 create_all。
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('audit_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('trace_id', sa.String(length=64), nullable=True),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('username', sa.String(length=64), nullable=True),
        sa.Column('action', sa.String(length=32), nullable=False),
        sa.Column('object_type', sa.String(length=32), nullable=True),
        sa.Column('object_id', sa.String(length=64), nullable=True),
        sa.Column('result', sa.String(length=16), nullable=False),
        sa.Column('ip', sa.String(length=64), nullable=True),
        sa.Column('user_agent', sa.String(length=255), nullable=True),
        sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
        op.create_index('ix_audit_log_user', 'audit_log', ['user_id', 'created_at'], unique=False)
        op.create_table('clause_ref',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('src_clause_id', sa.BigInteger(), nullable=False),
        sa.Column('src_clause_no', sa.String(length=64), nullable=True),
        sa.Column('dst_clause_id', sa.BigInteger(), nullable=True),
        sa.Column('dst_clause_no', sa.String(length=64), nullable=True),
        sa.Column('dst_spec_code', sa.String(length=64), nullable=True),
        sa.Column('relation', sa.String(length=32), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('source', sa.String(length=16), nullable=False),
        sa.Column('evidence', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_clause_ref_dst', 'clause_ref', ['dst_clause_no'], unique=False)
        op.create_index('ix_clause_ref_src', 'clause_ref', ['src_clause_id', 'relation'], unique=False)
        op.create_table('human_feedback',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('report_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('action', sa.String(length=32), nullable=False),
        sa.Column('dimension', sa.String(length=32), nullable=True),
        sa.Column('original_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('corrected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('knowledge_base',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('specialty', sa.String(length=64), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('retrieval_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
        op.create_table('llm_call_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('trace_id', sa.String(length=64), nullable=True),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('scene', sa.String(length=32), nullable=True),
        sa.Column('provider', sa.String(length=32), nullable=True),
        sa.Column('model', sa.String(length=64), nullable=True),
        sa.Column('is_fallback', sa.Boolean(), nullable=False),
        sa.Column('prompt_tokens', sa.Integer(), nullable=False),
        sa.Column('completion_tokens', sa.Integer(), nullable=False),
        sa.Column('total_tokens', sa.Integer(), nullable=False),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('project',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('owner_org', sa.String(length=128), nullable=True),
        sa.Column('supervision_org', sa.String(length=128), nullable=True),
        sa.Column('specialty', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
        )
        op.create_table('sys_user',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('full_name', sa.String(length=64), nullable=True),
        sa.Column('email', sa.String(length=128), nullable=True),
        sa.Column('phone', sa.String(length=32), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=False),
        sa.Column('project_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('failed_login_count', sa.Integer(), nullable=False),
        sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
        )
        op.create_index('ix_sys_user_role', 'sys_user', ['role'], unique=False)
        op.create_table('system_config',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('key', sa.String(length=64), nullable=False),
        sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('category', sa.String(length=32), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('updated_by', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key')
        )
        op.create_table('eval_task',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('project_id', sa.BigInteger(), nullable=True),
        sa.Column('user_id', sa.BigInteger(), nullable=True),
        sa.Column('eval_type', sa.String(length=32), nullable=False),
        sa.Column('specialty', sa.String(length=64), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('current_state', sa.String(length=24), nullable=False),
        sa.Column('current_step', sa.String(length=32), nullable=True),
        sa.Column('iteration_count', sa.Integer(), nullable=False),
        sa.Column('no_progress_rounds', sa.Integer(), nullable=False),
        sa.Column('progress', sa.Float(), nullable=False),
        sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('guard_reason', sa.Text(), nullable=True),
        sa.Column('checkpoint_thread_id', sa.String(length=64), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('total_tokens', sa.Integer(), nullable=False),
        sa.Column('total_cost', sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_eval_task_project', 'eval_task', ['project_id'], unique=False)
        op.create_index('ix_eval_task_state', 'eval_task', ['current_state'], unique=False)
        op.create_index('ix_eval_task_user', 'eval_task', ['user_id', 'created_at'], unique=False)
        op.create_table('spec_doc',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('kb_id', sa.BigInteger(), nullable=True),
        sa.Column('spec_code', sa.String(length=64), nullable=False),
        sa.Column('spec_name', sa.String(length=255), nullable=False),
        sa.Column('issuer', sa.String(length=128), nullable=True),
        sa.Column('publish_date', sa.Date(), nullable=True),
        sa.Column('effective_date', sa.Date(), nullable=True),
        sa.Column('abolish_date', sa.Date(), nullable=True),
        sa.Column('specialty', sa.String(length=64), nullable=True),
        sa.Column('region_level', sa.String(length=32), nullable=True),
        sa.Column('scope', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('uploader_id', sa.BigInteger(), nullable=True),
        sa.Column('remark', sa.Text(), nullable=True),
        sa.Column('kg_built', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['kb_id'], ['knowledge_base.id'], ),
        sa.ForeignKeyConstraint(['uploader_id'], ['sys_user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('spec_code', 'specialty', name='uq_spec_code_specialty')
        )
        op.create_index('ix_spec_doc_specialty', 'spec_doc', ['specialty'], unique=False)
        op.create_index('ix_spec_doc_status', 'spec_doc', ['status'], unique=False)
        op.create_table('agent_step_log',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('step', sa.String(length=32), nullable=False),
        sa.Column('seq', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('token_used', sa.Integer(), nullable=False),
        sa.Column('iteration', sa.Integer(), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('output_digest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['eval_task.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_agent_step_task', 'agent_step_log', ['task_id', 'seq'], unique=False)
        op.create_table('doc_version',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('doc_id', sa.BigInteger(), nullable=False),
        sa.Column('version_label', sa.String(length=64), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=512), nullable=False),
        sa.Column('file_size', sa.BigInteger(), nullable=True),
        sa.Column('file_hash', sa.String(length=64), nullable=True),
        sa.Column('file_type', sa.String(length=16), nullable=True),
        sa.Column('page_count', sa.Integer(), nullable=True),
        sa.Column('parse_status', sa.String(length=16), nullable=False),
        sa.Column('parse_error', sa.Text(), nullable=True),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('chunk_count', sa.Integer(), nullable=False),
        sa.Column('parse_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['doc_id'], ['spec_doc.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_doc_version_doc', 'doc_version', ['doc_id', 'is_current'], unique=False)
        op.create_table('eval_report',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('conclusion', sa.Text(), nullable=True),
        sa.Column('overall_verdict', sa.String(length=24), nullable=True),
        sa.Column('risk_level', sa.String(length=8), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('markdown', sa.Text(), nullable=True),
        sa.Column('basis_count', sa.Integer(), nullable=False),
        sa.Column('non_compliance_count', sa.Integer(), nullable=False),
        sa.Column('generator_model', sa.String(length=64), nullable=True),
        sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_final', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['eval_task.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id')
        )
        op.create_table('eval_subtask',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('seq', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('criterion', sa.Text(), nullable=True),
        sa.Column('required_evidence', sa.Text(), nullable=True),
        sa.Column('specialty', sa.String(length=64), nullable=True),
        sa.Column('query', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['eval_task.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_eval_subtask_task', 'eval_subtask', ['task_id', 'seq'], unique=False)
        op.create_table('match_result',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('subtask_id', sa.BigInteger(), nullable=True),
        sa.Column('clause_id', sa.BigInteger(), nullable=True),
        sa.Column('clause_no', sa.String(length=64), nullable=True),
        sa.Column('spec_code', sa.String(length=64), nullable=True),
        sa.Column('spec_name', sa.String(length=255), nullable=True),
        sa.Column('verdict', sa.String(length=24), nullable=False),
        sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column('relevance_score', sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column('evidence', sa.Text(), nullable=True),
        sa.Column('reasoning', sa.Text(), nullable=True),
        sa.Column('risk_level', sa.String(length=8), nullable=True),
        sa.Column('remediation', sa.Text(), nullable=True),
        sa.Column('citation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['task_id'], ['eval_task.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_match_result_task', 'match_result', ['task_id'], unique=False)
        op.create_index('ix_match_result_verdict', 'match_result', ['verdict'], unique=False)
        op.create_table('doc_chunk',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('doc_version_id', sa.BigInteger(), nullable=False),
        sa.Column('doc_id', sa.BigInteger(), nullable=False),
        sa.Column('clause_no', sa.String(length=64), nullable=True),
        sa.Column('chapter_path', sa.String(length=512), nullable=True),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('page_no', sa.Integer(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('token_count', sa.Integer(), nullable=True),
        sa.Column('faiss_id', sa.BigInteger(), nullable=True),
        sa.Column('embedding_model', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['doc_version_id'], ['doc_version.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_doc_chunk_clause', 'doc_chunk', ['clause_no'], unique=False)
        op.create_index('ix_doc_chunk_doc', 'doc_chunk', ['doc_id', 'status'], unique=False)
        op.create_index('ix_doc_chunk_faiss', 'doc_chunk', ['faiss_id'], unique=False)
        op.create_table('judge_review',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('report_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('judge_model', sa.String(length=64), nullable=True),
        sa.Column('total_score', sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column('grade', sa.String(length=16), nullable=True),
        sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('citation_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('has_conflict', sa.Boolean(), nullable=False),
        sa.Column('needs_human', sa.Boolean(), nullable=False),
        sa.Column('threshold', sa.Float(), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['report_id'], ['eval_report.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_judge_review_report', 'judge_review', ['report_id'], unique=False)
        op.create_table('judge_score',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('report_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('review_id', sa.BigInteger(), nullable=True),
        sa.Column('judge_model', sa.String(length=64), nullable=True),
        sa.Column('dimension', sa.String(length=32), nullable=False),
        sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('is_conflict', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['report_id'], ['eval_report.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['review_id'], ['judge_review.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_judge_score_dim', 'judge_score', ['dimension'], unique=False)
        op.create_index('ix_judge_score_report', 'judge_score', ['report_id'], unique=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    """回退：按依赖倒序删除全部表。"""
    op.drop_table("system_config")
    op.drop_table("llm_call_log")
    op.drop_table("audit_log")
    op.drop_table("human_feedback")
    op.drop_table("judge_score")
    op.drop_table("judge_review")
    op.drop_table("eval_report")
    op.drop_table("agent_step_log")
    op.drop_table("match_result")
    op.drop_table("eval_subtask")
    op.drop_table("eval_task")
    op.drop_table("clause_ref")
    op.drop_table("doc_chunk")
    op.drop_table("doc_version")
    op.drop_table("spec_doc")
    op.drop_table("knowledge_base")
    op.drop_table("sys_user")
    op.drop_table("project")
